spring.application.name=CarRent

# Use MongoDB only
spring.data.mongodb.uri=mongodb://localhost:27017/car
server.port=8080
# Disable JDBC auto-config
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
